services:
  - type: web
    name: verselor-v1
    repo: https://github.com/HeavstalTech/Verselor-V1.git
    branch: main
    runtime: docker
    dockerfilePath: Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: 3000
